### ISSUE TITLE
always lying down

### ISSUE THREAD

**Issue by zw199502** [qiayuanliao/legged_control#15]
following the quick start, why are both the simulated and real A1 robots lying down?
When I selected the trot gait, the robot did trot but the robot base was close to the ground.

**Comment by qiayuanliao** [comment]
Read the document carefully!

**Comment by elpimous** [comment]
@zw199502  You missed : 
rosservice call /controller_manager/switch_controller "start_controllers: ['controllers/legged_controller']                   
stop_controllers: ['']
strictness: 0
start_asap: false
timeout: 0.0"

**Comment by BolunDai0216** [comment]
Very useful, should update the readme to make this more obvious. @qiayuanliao  I can do a PR if that't fine with you.
