### ISSUE TITLE
Inquire About Real Robots Startup

### ISSUE THREAD

**Issue by liukaishu** [qiayuanliao/legged_control#18]
Hello, thank you for sharing such an excellent project. It has been successfully run in the simulation environment. I would like to ask how the real robot works. Following your steps, it won't start. Run "ros launch legged_unitree_hw legged_unitree_hw.launch
"After that, the error "Failed to set threads priority (one possible reason could be that the user and the group permissions are not set properly.)." will appear.

**Comment by qiayuanliao** [comment]
This msg is a warning, you can ignore it if you running this program without high load. However, check [faq](https://leggedrobotics.github.io/ocs2/faq.html) to solve this problem.
