### ISSUE TITLE
T265 use and legged_cheater_controller physical use problem

### ISSUE THREAD

**Issue by 123FengzhiLi123** [qiayuanliao/legged_control#23]
Hello, I see in your video, there is T265, how is this piece added and used, and why the command legged_cheater_controller is not allowed in the actual product, thank you for sharing this project

**Comment by qiayuanliao** [comment]
1. Rigid attach the T265 to the robot's body
2. Add the URDF of T265 to the robot.xarco correctly
3. Remap the T265's output topic to /tracking_camera/odom/sample

The [stateEstimator](https://github.com/qiayuanliao/legged_control/blob/master/legged_estimation/src/LinearKalmanFilter.cpp#L164) will receive data from T265 and handle all transformations, then overwrite the robot position with data from T265.
