### ISSUE TITLE
Imported target "Boost::system" includes non-existent path "/include" (from ocs2_core)

### ISSUE THREAD

**Issue by elpimous** [qiayuanliao/legged_control#25]
did you ever seen that ?

here is the terminal catkin build error.
https://pastebin.com/Nus2c0fs

the catkin_build : catkin build ocs2_legged_robot_ros ocs2_self_collision_visualization

system : i86 UP extreme i7

Don't know to do. tested many times, and with new fresh ros.
Thanks the team.
Vincent

**Comment by qiayuanliao** [comment]
The packages you built are pure OCS2s, so you might open an issue in the OCS2 repo.

**Comment by elpimous** [comment]
Correct. I didit, thanks
