### ISSUE TITLE
any possibility to make permanent  Shared Libraries ?

### ISSUE THREAD

**Issue by elpimous** [qiayuanliao/legged_control#27]
hello the team.
At each run, there is lots of compilations : 
`[CppAdInterface] Compiling Shared Library: /tmp/legged_control/a1/dynamics_systemFlowMap/cppad_generated/dynamics_systemFlowMap_libcppadcg_tmp7655064.so`...

Is it a way to make permanent those shared libs, to facilitate startup ?
Thanks, 
Vincent

**Comment by qiayuanliao** [comment]
Maybe some simple script running in each power may work.
