### ISSUE TITLE
Question about linear_kalman_filter

### ISSUE THREAD

**Issue by skywoodsz** [qiayuanliao/legged_control#3]
Hi, I have some questions about your linear kalman filter.cpp.

In Mit Cheetah program, they let 
$$
x = [{}^op_{com}, {}^ov_{com}, {}^op_i]^T
$$

where represents the position of COM, the velocity of COM and the position of foot in the world frame, respectively.  Therefore their c matrix is

```c++
 _C.block(0, 6, 12, 12) = T(-1) * Eigen::Matrix<T, 12, 12>::Identity();
```

But in your linear Kalman filter, your  c matrix is

```c++
c_.block(0, 6, 12, 12) = Eigen::Matrix<scalar_t, 12, 12>::Identity();
```

What's the difference between your filter and MIT's filter?  What variable does y represent in your program? Can you give me some advice, thanks！

**Comment by qiayuanliao** [comment]
It's a typo of mine, the reason why the program still working is I didn't use the foot position from the kalman filter in other places. I will fixed it in the latest commit.
