### ISSUE TITLE
The center of pressure always offset, How to solve it?

### ISSUE THREAD

**Issue by zhuiyuehun** [qiayuanliao/legged_control#30]
Hello,Mr Liao,  I apply to go1 robot ,  as the title describes, the center of gravity always offset,even if I adjust to the middle position when it on stance mode, but change the  mode to “trot”,it offset too.  
![IMG_0016](https://user-images.githubusercontent.com/34757181/223363082-6db6e801-c0b4-442b-a4fe-cfe46f0a9cb2.jpeg)
And second question , The order of force data of “current state.input” is “LF LH RF RH” ,or.  ”LF RF LH   RH ”?

**Comment by qiayuanliao** [comment]
There may be a bias in imu's orientation output. Or the CoM of Go1 is not in the geometry center of the torso.

LF, LH, RF, RH.

**Comment by zhuiyuehun** [comment]
Thank for your answer. If the center of gravity is not at the geometric center  and offset so large distance, Can this repository handle it?

**Comment by qiayuanliao** [comment]
Yes

**Comment by LianzhaoZhang** [comment]
Hello, I think I'm experiencing a similar issue to yours. When I press the deadman buttons on the joy to publish /cmd_vel, the robot consistently drifts to the left rear. I recalibrated the ground contact threshold to ensure accurate contact state updates and increased the control frequency to 1000Hz. While these changes somewhat alleviated the problem, it still persists. Could you share how you resolved this issue - did you recalibrate the center of gravity position, or did you use other methods?

Additionally, I'm uncertain whether the robot's center of pressure (COP) displayed in RViz is calculated from the actual contact forces and foot positions read from the robot's foot sensors. If it is indeed based on sensor contact forces, I suspect this position of COP might be inaccurate. When I consulted Unitree's technical support, they informed me that these sensors are only meant for ground contact detection and have significant error margins. On my quadruped robot, there are considerable discrepancies in the force readings between different foot endpoints.
