### ISSUE TITLE
is /tracking_camera/odom/sample needed for hardware controller ??

### ISSUE THREAD

**Issue by elpimous** [qiayuanliao/legged_control#36]
Hello, I see the /tracking_camera/odom/sample !!!
Is it needed for real robot odom ??
Thanks

**Comment by BolunDai0216** [comment]
> Hello, I see the /tracking_camera/odom/sample !!! Is it needed for real robot odom ?? Thanks
> 
> Update : not needed!

Hi @elpimous, would it be possible to provide some details about what you did to remove the visual odometry?
