### ISSUE TITLE
Gazebo real time factor decrease to 0.05 after starting legged_controller

### ISSUE THREAD

**Issue by Atom990** [qiayuanliao/legged_control#4]
When the gazebo world was launched, the time factor is 1.00. But after I started the legged_controller in rqt_controller_manager, the time factor decreased to only 0.05. My computer has RTX 3080, AMD Ryzen 9 5900HS, 16GB DDR4, and is good at running other Gazebo simulations. Is this normal?

**Comment by qiayuanliao** [comment]
I guess you are using the debug build type instead of release, try
```
catkin config -DCMAKE_BUILD_TYPE=RelWithDebInfo
```
