### ISSUE TITLE
real robot stand-up steps

### ISSUE THREAD

**Issue by elpimous** [qiayuanliao/legged_control#43]
Hi all,
Trying to standup my robot (not a unitree one),

1/ run the robot hardware : `roslaunch legged_unitree_hw legged_unitree_hw.launch`
    * calibration, and initialization
  
2/ run the controller          : `roslaunch legged_controllers load_controller.launch`
    * loads shared libs
  
3/ run the legged_controller : 

```
rosservice call /controller_manager/switch_controller "start_controllers: ['controllers/legged_controller']                   
stop_controllers: ['']
strictness: 0
start_asap: false
timeout: 0.0" 
```

In this step, legs are moving, and shaking !!  

**question1** / Do legs want to reach initial pose ? Where to modify the pose ?

**question2** / The robot shouldn't move, until I send the `rostopic pub -1 /cmd_vel...`, correct ?

**Comment by elpimous** [comment]
Legs shouldn't move before the cmd_vel command. (for legs extention) 
why do they move?
Params in reference and task info are for robot up.
could it be a Urdf bad value?

**Comment by elpimous** [comment]
urdf ok ! same problem : 
here is my rviz topics : 
![Capture d’écran de 2023-06-15 22-40-31](https://github.com/qiayuanliao/legged_control/assets/8529940/db4b8e78-af1f-4150-9a7b-a76f7cfa6e29)
![Capture d’écran de 2023-06-15 22-40-34](https://github.com/qiayuanliao/legged_control/assets/8529940/86b55f48-0f84-4d6f-ad26-66b976ed104d)

**Comment by elpimous** [comment]
Small up, friends ?

**Comment by elpimous** [comment]
UP please

**Comment by elpimous** [comment]
solved, problem of unsigned fftorque !

**Comment by hassan-mehmood1** [comment]
Hi @elpimous,
Can you tell me how did you resolve the issue. I am also working on a custom robot and legs are moving when I start the code without giving any cmd_vel command.

Thanks
