### ISSUE TITLE
运行roslaunch ocs2_legged_robot_ros legged_robot_ddp.launch rviz中机器狗优化轨迹显示报错，机器狗静止

### ISSUE THREAD

**Issue by dbdxnuliba** [qiayuanliao/legged_control#50]
roslaunch ocs2_legged_robot_ros legged_robot_ddp.launch

![image](https://github.com/qiayuanliao/legged_control/assets/13350158/cac8fb87-c70e-44b6-a2f3-eb0227b80457)

**Comment by dbdxnuliba** [comment]
好了，看到选项了
![image](https://github.com/qiayuanliao/legged_control/assets/13350158/7b4ce0f7-f5d1-4ff1-b485-6d0e9e97405b)

**Comment by MoonGreat** [comment]
me,too。。。angry!
