### ISSUE TITLE
Unable to load robot model (dae files) in Rviz

### ISSUE THREAD

**Issue by lucasbrodo** [qiayuanliao/legged_control#52]
Hi,
I'm getting this error (`: Could not load resource [/home/lucas/legged_control_ws/src/legged_control/legged_examples/legged_unitree/legged_unitree_description/meshes/go1/calf.dae]: Unable to open file "/home/lucas/legged_control_ws/src/legged_control/legged_examples/legged_unitree/legged_unitree_description/meshes/go1/calf.dae"`) when trying to load `legged_robot_description` in Rviz. The files are correctly present in the `meshes/go1` folder.

![image](https://github.com/qiayuanliao/legged_control/assets/94857159/dcfb3a8a-b2b4-462d-87c6-34a6b670d0a2)

Thanks for your help !

**Comment by mitsui29** [comment]
hey, i got the same problem with u. but i think this line u mentioned here, it has been added to the robot.xacro, but i still got the same problem. Do u have some ideas?thx a lot!
![2023-11-04 01-31-13 的屏幕截图](https://github.com/qiayuanl/legged_control/assets/95944211/167f90a9-32af-4dda-9b60-78d263c6c411)

**Comment by lucasbrodo** [comment]
![image](https://github.com/qiayuanl/legged_control/assets/94857159/4428005d-cb54-449e-b068-b82b4babe9db)
This is the file you should have.
Then make sure the frame in rviz is `odom` not `base` (see issue #47)

Hope it helps.

**Comment by lucasbrodo** [comment]
Also make sure to activate the controller :
```
rosservice call /controller_manager/switch_controller "start_controllers: ['controllers/legged_controller']                   
stop_controllers: ['']
strictness: 0
start_asap: false
timeout: 0.0" 
```
